# action.yml
name: 'Create GPU'
description: 'Deploy GPU and provide connection details'
inputs:
  access-key:
    description: 'access-key'
    required: true
    default: 'access-key'
  secret-key:
    description: 'secret-key'
    required: true
    default: 'secret-key'
  uuid:
    description: 'uuid of gpu to delete'
    required: true
outputs:
  success:
    description: 'success flag'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-key }}
    - ${{ inputs.secret-key }}
    - ${{ inputs.uuid }}